POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "Always Validate your data before posting.",
    "important": true
}

###

GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/notes/680b13071a782046f36f9ss9